### ISSUE TITLE
Adapt demo + code to polymer 1.0

### ISSUE THREAD

**Issue by micbuffa** [g200kg/webaudio-controls#10]
Hi! I tried webaudio controls with a version forked by ryoyakawai (this one: https://github.com/ryoyakawai/webaudio-controls/tree/submissions/polymer0.8) altogether with polymer 1.0 and it works pretty well, I had zero problem upgrading my application (https://mainline.i3s.unice.fr/AmpSim). Maybe you should merge your version with this one that is still relying on Polymer 0.5. You should also update the demo site that raises warnings on Chrome that say that it will stop working with Chrome version 50.

**Comment by g200kg** [comment]
updated
