### ISSUE TITLE
2 grouped webaudio-switches that can both be off

### ISSUE THREAD

**Issue by abulka** [g200kg/webaudio-controls#11]
Any ideas on how I can have 2 webaudio-switches that are mutually exclusive, and there is a way of turning them both OFF?  For exxample by clicking on a switch that is on, it will go off (without turning the other switch on).

I am implementing a synthesizer and there is are two lights and I need

- light 1 on
- light 2 on
- both lights off

This code from the doco gives me mutually exclusive buttons
```
<webaudio-switch id="radioA" src="img/switch_toggle.png" type="radio" group="radio1" width="54" height="54" value="1" tooltip="Radio-A"></webaudio-switch>
<webaudio-switch id="radioB" src="img/switch_toggle.png" type="radio" group="radio1" width="54" height="54" tooltip="Radio-B"></webaudio-switch&bt;
<webaudio-switch id="radioC" src="img/switch_toggle.png" type="radio" group="radio1" width="54" height="54" tooltip="Radio-C"></webaudio-switch>

Radio type switch. In this mode, only one switch is activated in the group.
```

but I also need a mode where both switches are off.  Any ideas?
Thanks.

**Comment by g200kg** [comment]
For now, there is no option about that.
But following code may be a help.

    <webaudio-switch id="radioA" type="toggle" group="a" value="1"></webaudio-switch>
    <webaudio-switch id="radioB" type="toggle" group="a"></webaudio-switch>
    <webaudio-switch id="radioB" type="toggle" group="a"></webaudio-switch>

In current implementation,
type="toggle" means on/off toggle the pressed switch.
type="radio" means pressed switch is on anyway.
and the group attribute means automatic off when other switch in the group is on.
then the "toggle" and group combination will do desired operation.

this is not officially defined behavior but I think it is useful.

**Comment by abulka** [comment]
That works and solves my problem - thanks very much!

P.S. Thanks for making this library - its  great.
