### ISSUE TITLE
setValue() of switches always fires event despite false param

### ISSUE THREAD

**Issue by abulka** [g200kg/webaudio-controls#12]
The `fire` parameter in the call `setValue(value, fire)` has no effect for `webaudio-switch` (bug?) but works OK for `webaudio-knob`

For example, after wiring in on change handlers for both knobs
```
  var knobs = document.getElementsByTagName('webaudio-knob');
  for (var i = 0; i < knobs.length; i++) {
    var knob = knobs[i];
    knob.addEventListener('change', function(e) {
      console.log(e.target.value, 'knob');
    });
  }
```
and switches
```
  var switches = document.getElementsByTagName('webaudio-switch');
  for (var i = 0; i < switches.length; i++) {
    var s = switches[i];
    s.addEventListener('change', function(e) {
      console.log(e.target.value, 'switch', $(e.target).attr('name'));
    });
  }
```

I get the knob change event firing as documented:
```
$('webaudio-knob[name="knob_lp_cutoff"]')[0].setValue(101, true)  // event triggered - OK
$('webaudio-knob[name="knob_lp_cutoff"]')[0].setValue(101, false)  // // event not triggered - OK
```
but the switch event fires all the time
```
$('webaudio-switch[name="toggle_lp_velocity"]')[0].setValue(1)  // event triggered ?
$('webaudio-switch[name="toggle_lp_velocity"]')[0].setValue(1, false)  // event triggered ?
```
(of course when testing, ensure UI state of the switch is opposite to what you are setting it to in the code, otherwise nothing will trigger due only to the fact that no change was needed).

**Comment by g200kg** [comment]
Thank you, It is a bug.
Now fixed.

**Comment by abulka** [comment]
Thanks - much improved.  However I'm still getting switch events firing on the _other_ switch controls of a group.  So if there is a group with A & B and you `A.setValue(1, false)`, no event will fire on A (good), but an event will still fire on B (bad?).  

I think these are unwanted events especially when I'm programmatically setting up a UI from scratch.  However possibly somebody could argue that these side effect effects should stay?  My vote is for no side effect events.

**Comment by g200kg** [comment]
Indeed.
Though this behavior may be a doubt in some cases, I agree to no side effects.
I already fixed it.

Thank you

**Comment by abulka** [comment]
Perfect - now works OK.
Thanks!
