### ISSUE TITLE
Polymer 2 version of WebAudio controls here!

### ISSUE THREAD

**Issue by micbuffa** [g200kg/webaudio-controls#20]
Hi! Just to let you know that we ported the last version of webaudiocontrols to Polymer 2 yesterday. We're testing them today + also with the webcomponent V1 polyfill, to be sure that they still work ok on all browsers.

We also noticed something strange with FF (with the current version): when we try the sample 1 demo and use two fingers sliding up and down to change a knob value, with Chrome, Opera, Safari, it works, but with FF, it also scrolls up/down the document. We're also trying to understand what is going on... I don't know if you noticed this....

Polymer 2 version coming certainly today... Maybe you should create another branch? I'll first commit it to my fork, then you can try the version, and decide if you merge, make a new branch... ?

**Comment by micbuffa** [comment]
Here are Polymer webaudiocontrols examples that should work on nearly all recent browsers, as we also imported the WebComponents V1 polyfill:

- https://wasabi.i3s.unice.fr/AmpSimFA/g200kg/sample1.html
- https://wasabi.i3s.unice.fr/AmpSimFA/g200kg/sample2.html
- https://wasabi.i3s.unice.fr/AmpSimFA/g200kg/sample3.html
- https://wasabi.i3s.unice.fr/AmpSimFA/g200kg/sample4.html

We updated webaudiocontrols.html to follow the new polymer2 syntax + updated the webcomponents + polyfill from the repo. We also deleted only 1 html import at the top of sample1... sample4.html

It's just an update to your last commit from 10 days ago.

In addition to the update we also fixes in sliders and knobs the wheel event listener that made the page scroll at the same time as sliders/knobs where moving while using the mouse wheel/two fingers + slide, on FF. On other browsers, only the knobs/sliders moved, no scroll of the page.

This is fixed in this version too.

I did not made a pull request, as you may want to have another branch or another repo for this version?

**Comment by g200kg** [comment]
Thanks a lot!! 
I have still dithering to make new repo for Polymer 2 version. I think a little about what to do.

**Comment by micbuffa** [comment]
Hi g200kg, I've just updated the polymer2 version of webaudiocontrols so that they match 100% your polymer 1 version. Here is the repo: https://github.com/micbuffa/webaudio-controls

And here is the sample1.html demo online, that runs with this version + polymer 2 + polyfill (tested with FF/Chrome/Safari last stable versions).

Maybe it's time to update to Polymer 2?

**Comment by g200kg** [comment]
I've almost rewrite to use raw WebComponents API and no other library is required.

**Comment by micbuffa** [comment]
Good news, I saw your other repo that is pure JS, having no dependency would be great. BTW, with people from Faust and from WebAudioModules, we're working on a proposal for an open standard for WebAudio plugins. For this it's much better if plugins do not bring a Polymer dependency. If you have Chrome Canary you can check https://wasabi.i3s.unice.fr/pedalboard, drag and drop synths, effects, connect them (example video: https://www.youtube.com/watch?v=elbjh6tBK6U&t=31s). We mixed here the synths from WebAudioModules, an effect produced by the FAUST compiler, and the pure WebAudio / JS effects we wrote. We do not have the WAM code locally, we just import it from a remote URL. All plugins are WebComponents.

We're also writing a "plugin tester" right now. I'd really like to discuss this with with you as I already planned to turn some of your work into plugins (your tinysynth for example). Our host uses polymer 2, and we can have plugins that have this dependency, but in that case they need to use the same URL we use, otherwise it will not work. So we also started to remove polymer from some of our plugins, and having a Polymerless webaudiocontrols will be very helpful for that.

Can you send me an email so that we can start a discussion?

**Comment by g200kg** [comment]
Hi,　I just sent you a mail.
Thank you!
