### ISSUE TITLE
Multitouch controls

### ISSUE THREAD

**Issue by dburongarcia** [g200kg/webaudio-controls#24]
Hello, I wonder if all the controls could be used in a multitouch environment. Being able to use multiple sliders/knobs at the same time would be wonderful.

**Comment by g200kg** [comment]
I agree.
It's a little difficult, but that's what I like to do as well.

**Comment by g200kg** [comment]
Now multi touch is supported. check the demo,

https://g200kg.github.io/webaudio-controls/2.0/multifader.html

**Comment by dburongarcia** [comment]
It's working great! How did you manage to eliminate the scrolling and
zooming? It's also very accurate and I can even change the values just
tilting my fingers in the same position.

I tested your controls in some of your other demos and in my own code and
although I could control multiple sliders and knobs, it was a
nightmare on Chrome
because of all the scrolling and zooming.

Great job! Let me know if you need some more testing or anything else.

2018-02-05 19:29 GMT+01:00 g200kg <notifications@github.com>:
