### ISSUE TITLE
How can I have a logarithmic knob?

### ISSUE THREAD

**Issue by jordanSI06** [g200kg/webaudio-controls#29]
Hi; in earlier, polymer based versions of webaudiocontrols, there was a log html attribute for creating logarithmic knobs. I see now this conv attribute. I guess that I should use this instead but I don't really know how to proceed. Can you give an example of a logarithmic knob ? Thanks in advance. I'm controlling it through a midi expression pedal.

Jordan

**Comment by g200kg** [comment]
The "log" attribute has been restored.
Also added documentation:

https://g200kg.github.io/webaudio-controls/docs/nonlinear.html

**Comment by logpot** [comment]
For a log taper that can go to 0, see [taper.js](https://gitlab.com/-/snippets/2037358)
