### ISSUE TITLE
Responsive design

### ISSUE THREAD

**Issue by tcipierre** [g200kg/webaudio-controls#6]
Hi everyone,

First of all, thanks for the tremendous work on those pretty convenient Polymer audio tools !

However we can only specifiy a fixed width (in pixel) to all elements. Is there any plan in the future to make it responsive to the window size ?

For instance, a 61 keys keyboard of 900px is quite difficult to handle on small screens. I have tried to update the keyboard's attributes for `keys` and `min`, but although the `console.log` sends me the right updated attributes, the visual is not updated at all :

``` javascript
function rescaleKeyboard() {
    if (window.innerWidth >= '1320') {
        keyboard.keys = "61";
        keyboard.min='24';
        console.log(keyboard.getAttribute('keys'));
    } else if (window.innerWidth <= '1200') {
        keyboard.setAttribute("keys","49");
        keyboard.setAttribute("min","36");
        console.log(keyboard.getAttribute('keys'));
    }
}

window.addEventListener('resize', rescaleKeyboard);
```

Any idea or tip on the subject is more than welcome !

Thanks for reading and all the best,

**Comment by askdesigners** [comment]
I think a pretty big rewrite would be needed if you want to really support smaller devices. The image sprites for the knobs are also huge. 

I've been wanting to rewrite that part to use svgs and css transforms. I think that would make the whole system a lot more versatile.

**Comment by tcipierre** [comment]
Hi askdesigners,

Thanks a lot for your answer. That would be great, for sure!

I have unsuccessfully tried to change some tiny parts in the `polymer-elements`, but I don't have the time to go further, neither do I have the skills at the moment. However I can already tell you that you can use `.svg` files for `webaudio-knob` and `webaudio-slider` instead of `.png`, which is not a bad start ;).

**Comment by askdesigners** [comment]
I'd love to get a chance to poke around on it too. :)

**Comment by micbuffa** [comment]
You can wrap all your GUI or parts of your GUI in a div and use a CSS transform:scale(...,...), it works pretty well. Like that you can make your GUI responsive. I've done a guitar amp simulator with webaudio controls and it resizes pretty well.

**Comment by g200kg** [comment]
Now, changing keyboard.keys or keyboard.min reflects immediately on the display.
But note that this is effective only for direct property value change, not for setAttrubute().

Like this :
```
function rescaleKeyboard() {
    if (window.innerWidth >= '1320') {
        keyboard.keys = 61;
        keyboard.min = 24;
    } else if (window.innerWidth <= '1200') {
        keyboard.keys = 49;
        keyboard.min = 36;
    }
}
window.addEventListener('resize', rescaleKeyboard);
```
