### ISSUE TITLE
Knob: counter-intuitive when changing after 12 o'clock

### ISSUE THREAD

**Issue by HenningKlokkeraasen** [g200kg/webaudio-controls#9]
When the webaudio-knob is in a position after the middle point (12 o'clock) and you click + drag it down, the knob (and it's value) goes up, and vice versa. This is (imho) counter-intuitive, I expect it to go down when I click + drag down, since a knob is something circular (compared to a slider which only goes up and down not circular)

**Comment by g200kg** [comment]
webaudio-constols is supposed to be used in audio software like VST plugins. In these software, generally two types of knob mode is used. One is 'circular' mode that is depend on angle to knob-center  but this mode is not so popular. I think another one mode, 'linear' that same as webaudio-controls is used in almost cases.

**Comment by HenningKlokkeraasen** [comment]
Could it be a setting/parameter to webaudio-knob? I'll fork and try to implement this for my own needs at least. Would you consider a PR for this in this repo?

**Comment by g200kg** [comment]
It is welcome if you implement 'circular'/'linear' setting same as VST plugins even I think it will not be a default behavior.

**Comment by micbuffa** [comment]
I like the default behavior as it is by default. I don't feel it counter intuitive (!)
